name: Fineract Docker build - ioTec

on:
  push:
    branches:
      - 1.9.0-iotec
  workflow_dispatch:


permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04
    environment: production
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Set up JDK 17
        uses: actions/setup-java@2c7a4878f5d120bd643426d54ae1209b29cc01a3 # tag=v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle
      - name: Build the image
        run: ./gradlew :fineract-provider:clean :fineract-provider:jibDockerBuild -x test

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push the image to GitHub Container Registry
        run: |
          docker tag fineract:latest ghcr.io/${{ github.repository }}/fineract:1.8.5
          docker push ghcr.io/${{ github.repository }}/fineract:1.8.5
